// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LD_blocks
arma::ivec LD_blocks(const arma::vec& chr, const arma::vec& pos, const arma::mat& LDB);
RcppExport SEXP _BRIER_LD_blocks(SEXP chrSEXP, SEXP posSEXP, SEXP LDBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type chr(chrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type pos(posSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type LDB(LDBSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_blocks(chr, pos, LDB));
    return rcpp_result_gen;
END_RCPP
}
// LD_sigma
arma::sp_mat LD_sigma(const arma::mat& X, const arma::uvec& blk, double tau);
RcppExport SEXP _BRIER_LD_sigma(SEXP XSEXP, SEXP blkSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type blk(blkSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    rcpp_result_gen = Rcpp::wrap(LD_sigma(X, blk, tau));
    return rcpp_result_gen;
END_RCPP
}
// cd_wgaussian_fit_ssr
List cd_wgaussian_fit_ssr(const arma::mat& X, const arma::vec& y, const arma::vec& wt, const arma::vec& multiplier, const std::string& penalty, const arma::vec& lam, double alpha, double gamma, double lam_max, int max_iter, double eps, int dfmax);
RcppExport SEXP _BRIER_cd_wgaussian_fit_ssr(SEXP XSEXP, SEXP ySEXP, SEXP wtSEXP, SEXP multiplierSEXP, SEXP penaltySEXP, SEXP lamSEXP, SEXP alphaSEXP, SEXP gammaSEXP, SEXP lam_maxSEXP, SEXP max_iterSEXP, SEXP epsSEXP, SEXP dfmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lam_max(lam_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(cd_wgaussian_fit_ssr(X, y, wt, multiplier, penalty, lam, alpha, gamma, lam_max, max_iter, eps, dfmax));
    return rcpp_result_gen;
END_RCPP
}
// cd_glm_fit_ssr
Rcpp::List cd_glm_fit_ssr(const arma::mat& X, const arma::vec& y, std::string family, const arma::vec& multiplier, std::string penalty, const arma::vec& lambda, double alpha, double gamma, double lam_max, int max_iter, int dfmax, double eps, bool user, bool warn);
RcppExport SEXP _BRIER_cd_glm_fit_ssr(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP multiplierSEXP, SEXP penaltySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP gammaSEXP, SEXP lam_maxSEXP, SEXP max_iterSEXP, SEXP dfmaxSEXP, SEXP epsSEXP, SEXP userSEXP, SEXP warnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lam_max(lam_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type user(userSEXP);
    Rcpp::traits::input_parameter< bool >::type warn(warnSEXP);
    rcpp_result_gen = Rcpp::wrap(cd_glm_fit_ssr(X, y, family, multiplier, penalty, lambda, alpha, gamma, lam_max, max_iter, dfmax, eps, user, warn));
    return rcpp_result_gen;
END_RCPP
}
// cd_wglm_fit_ssr
Rcpp::List cd_wglm_fit_ssr(const arma::mat& X, const arma::vec& y, const arma::vec& wt, std::string family, const arma::vec& multiplier, std::string penalty, const arma::vec& lambda, double alpha, double gamma, double lam_max, int max_iter, int dfmax, double eps, bool user, bool warn);
RcppExport SEXP _BRIER_cd_wglm_fit_ssr(SEXP XSEXP, SEXP ySEXP, SEXP wtSEXP, SEXP familySEXP, SEXP multiplierSEXP, SEXP penaltySEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP gammaSEXP, SEXP lam_maxSEXP, SEXP max_iterSEXP, SEXP dfmaxSEXP, SEXP epsSEXP, SEXP userSEXP, SEXP warnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lam_max(lam_maxSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type user(userSEXP);
    Rcpp::traits::input_parameter< bool >::type warn(warnSEXP);
    rcpp_result_gen = Rcpp::wrap(cd_wglm_fit_ssr(X, y, wt, family, multiplier, penalty, lambda, alpha, gamma, lam_max, max_iter, dfmax, eps, user, warn));
    return rcpp_result_gen;
END_RCPP
}
// cd_summary_fit
List cd_summary_fit(const arma::vec& XtY, const arma::sp_mat& ld_mat, const arma::vec& multiplier, const std::string& penalty, const arma::vec& lam, double alpha, double gamma, double eps, int max_iter, int dfmax, bool user);
RcppExport SEXP _BRIER_cd_summary_fit(SEXP XtYSEXP, SEXP ld_matSEXP, SEXP multiplierSEXP, SEXP penaltySEXP, SEXP lamSEXP, SEXP alphaSEXP, SEXP gammaSEXP, SEXP epsSEXP, SEXP max_iterSEXP, SEXP dfmaxSEXP, SEXP userSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type XtY(XtYSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type ld_mat(ld_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type multiplier(multiplierSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< int >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< bool >::type user(userSEXP);
    rcpp_result_gen = Rcpp::wrap(cd_summary_fit(XtY, ld_mat, multiplier, penalty, lam, alpha, gamma, eps, max_iter, dfmax, user));
    return rcpp_result_gen;
END_RCPP
}
// maxprod
double maxprod(const arma::mat& X, const arma::vec& r, int n, int p, const arma::vec& m);
RcppExport SEXP _BRIER_maxprod(SEXP XSEXP, SEXP rSEXP, SEXP nSEXP, SEXP pSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(maxprod(X, r, n, p, m));
    return rcpp_result_gen;
END_RCPP
}
// maxlambda_summary
double maxlambda_summary(const arma::vec& XtY, const arma::sp_mat& ld_mat, const arma::vec& m, double alpha, double eps, int max_iter);
RcppExport SEXP _BRIER_maxlambda_summary(SEXP XtYSEXP, SEXP ld_matSEXP, SEXP mSEXP, SEXP alphaSEXP, SEXP epsSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type XtY(XtYSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type ld_mat(ld_matSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(maxlambda_summary(XtY, ld_mat, m, alpha, eps, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// pseudo_validation
arma::vec pseudo_validation(const arma::mat& beta, const arma::sp_mat& XtX, const arma::vec& r);
RcppExport SEXP _BRIER_pseudo_validation(SEXP betaSEXP, SEXP XtXSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudo_validation(beta, XtX, r));
    return rcpp_result_gen;
END_RCPP
}
// standardize_X
List standardize_X(const NumericMatrix& Xr);
RcppExport SEXP _BRIER_standardize_X(SEXP XrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xr(XrSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize_X(Xr));
    return rcpp_result_gen;
END_RCPP
}
// wstandardize_X
List wstandardize_X(const arma::mat& X, const arma::vec& wt);
RcppExport SEXP _BRIER_wstandardize_X(SEXP XSEXP, SEXP wtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type wt(wtSEXP);
    rcpp_result_gen = Rcpp::wrap(wstandardize_X(X, wt));
    return rcpp_result_gen;
END_RCPP
}
// unstand_beta
arma::mat unstand_beta(arma::mat& b0, arma::mat& b, arma::vec& scale, arma::vec& center, double yy_center, int L, int p);
RcppExport SEXP _BRIER_unstand_beta(SEXP b0SEXP, SEXP bSEXP, SEXP scaleSEXP, SEXP centerSEXP, SEXP yy_centerSEXP, SEXP LSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type center(centerSEXP);
    Rcpp::traits::input_parameter< double >::type yy_center(yy_centerSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(unstand_beta(b0, b, scale, center, yy_center, L, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BRIER_LD_blocks", (DL_FUNC) &_BRIER_LD_blocks, 3},
    {"_BRIER_LD_sigma", (DL_FUNC) &_BRIER_LD_sigma, 3},
    {"_BRIER_cd_wgaussian_fit_ssr", (DL_FUNC) &_BRIER_cd_wgaussian_fit_ssr, 12},
    {"_BRIER_cd_glm_fit_ssr", (DL_FUNC) &_BRIER_cd_glm_fit_ssr, 14},
    {"_BRIER_cd_wglm_fit_ssr", (DL_FUNC) &_BRIER_cd_wglm_fit_ssr, 15},
    {"_BRIER_cd_summary_fit", (DL_FUNC) &_BRIER_cd_summary_fit, 11},
    {"_BRIER_maxprod", (DL_FUNC) &_BRIER_maxprod, 5},
    {"_BRIER_maxlambda_summary", (DL_FUNC) &_BRIER_maxlambda_summary, 6},
    {"_BRIER_pseudo_validation", (DL_FUNC) &_BRIER_pseudo_validation, 3},
    {"_BRIER_standardize_X", (DL_FUNC) &_BRIER_standardize_X, 1},
    {"_BRIER_wstandardize_X", (DL_FUNC) &_BRIER_wstandardize_X, 2},
    {"_BRIER_unstand_beta", (DL_FUNC) &_BRIER_unstand_beta, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_BRIER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
