# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LD Block Structured SNP grouping
#'
#' Calculate LD-block group boundaries for a list of SNPs given a pre-computed
#' block definition (Berisa et al.). The inputs must be sorted by chromosome and
#' position.
#'
#' @param chr Numeric vector of chromosome IDs (length n).
#' @param pos Numeric vector of base-pair positions (length n).
#' @param LDB Numeric matrix (m x 3) of (chr, start, stop) for each LD block.
#' @return Integer vector of length K+1 giving the 0-based index in (chr, pos)
#'         where each block starts, including the end marker at n.
#' @export
LD_blocks <- function(chr, pos, LDB) {
    .Call('_BRIER2_LD_blocks', PACKAGE = 'BRIER2', chr, pos, LDB)
}

#' Block-Structured LD Calculation
#'
#' Calculate LD matrix within blocks using soft-thresholding.
#'
#' @param X N x p standardized genotype matrix.
#' @param blk Vector of block boundaries of length K+1 (0-based).
#' @param tau Soft-threshold parameter.
#' @return p x p sparse LD matrix (arma::sp_mat).
#' @export
LD_sigma <- function(X, blk, tau) {
    .Call('_BRIER2_LD_sigma', PACKAGE = 'BRIER2', X, blk, tau)
}

#' Coordinate descent for weighted Gaussian regression with sequential strong rule
#'
#' Coordinate-descent algorithm for penalised weighted Gaussian regression with
#' sequential strong rule (SSR) screening over a sequence of penalty values.
#'
#' @param X A numeric matrix of predictors (n x p).
#' @param y A numeric response vector of length n.
#' @param wt A numeric vector of observation weights (length n).
#' @param multiplier A numeric vector of per-variable penalty multipliers (length p).
#'   Variables with multiplier = 0 are treated as unpenalised.
#' @param penalty A string specifying the penalty: "LASSO", "MCP", or "SCAD".
#' @param lam A numeric vector of penalty values, sorted in decreasing order.
#' @param alpha A numeric scalar for the elastic net mixing parameter.
#' @param gamma A numeric scalar for MCP and SCAD penalties.
#' @param lam_max A numeric scalar for the maximum lambda value (used in SSR cutoff).
#' @param max_iter An integer specifying the maximum total iterations allowed.
#' @param eps A numeric scalar for the convergence tolerance.
#' @param dfmax An integer specifying the maximum number of selected variables.
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{beta0}{A numeric vector of intercepts for each lambda.}
#'   \item{beta}{A matrix of coefficients (p x length(lam)).}
#'   \item{dev}{A numeric vector of weighted residual sums of squares.}
#'   \item{eeta}{A matrix of fitted linear predictors (n x length(lam)).}
#'   \item{df}{A numeric vector of degrees of freedom for each lambda.}
#'   \item{iter}{An integer vector of iteration counts for each lambda.}
#' }
cd_wgaussian_fit_ssr <- function(X, y, wt, multiplier, penalty, lam, alpha, gamma, lam_max, max_iter, eps, dfmax) {
    .Call('_BRIER2_cd_wgaussian_fit_ssr', PACKAGE = 'BRIER2', X, y, wt, multiplier, penalty, lam, alpha, gamma, lam_max, max_iter, eps, dfmax)
}

#' Coordinate descent for GLM with sequential strong rule
#'
#' Coordinate-descent algorithm for penalised generalised linear models (binomial
#' or Poisson) with sequential strong rule (SSR) screening over a sequence of
#' penalty values.
#'
#' @param X A numeric matrix of predictors (n x p).
#' @param y A numeric response vector of length n.
#' @param family A string: "binomial" or "poisson".
#' @param multiplier A numeric vector of per-variable penalty multipliers (length p).
#'   Variables with multiplier = 0 are treated as unpenalised.
#' @param penalty A string specifying the penalty: "LASSO", "MCP", or "SCAD".
#' @param lambda A numeric vector of penalty values, sorted in decreasing order.
#' @param alpha A numeric scalar for the elastic net mixing parameter.
#' @param gamma A numeric scalar for MCP and SCAD penalties.
#' @param lam_max A numeric scalar for the maximum lambda value (used in SSR cutoff).
#' @param max_iter An integer specifying the maximum total iterations allowed.
#' @param dfmax An integer specifying the maximum number of selected variables.
#' @param eps A numeric scalar for the convergence tolerance.
#' @param user A logical flag. If TRUE, lambda is user-specified and iteration starts
#'   from the first value; if FALSE, the first lambda is treated as the null model.
#' @param warn A logical flag. If TRUE, issues a warning when the model saturates.
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{beta0}{A numeric vector of intercepts for each lambda.}
#'   \item{beta}{A matrix of coefficients (p x length(lambda)).}
#'   \item{dev}{A numeric vector of deviance values.}
#'   \item{eeta}{A matrix of fitted linear predictors (n x length(lambda)).}
#'   \item{iter}{An integer vector of iteration counts for each lambda.}
#' }
cd_glm_fit_ssr <- function(X, y, family, multiplier, penalty, lambda, alpha, gamma, lam_max, max_iter, dfmax, eps, user = FALSE, warn = TRUE) {
    .Call('_BRIER2_cd_glm_fit_ssr', PACKAGE = 'BRIER2', X, y, family, multiplier, penalty, lambda, alpha, gamma, lam_max, max_iter, dfmax, eps, user, warn)
}

#' Coordinate descent for weighted GLM with sequential strong rule
#'
#' Coordinate-descent algorithm for penalised weighted generalised linear models
#' (binomial or Poisson) with sequential strong rule (SSR) screening over a
#' sequence of penalty values.
#'
#' @param X A numeric matrix of predictors (n x p).
#' @param y A numeric response vector of length n.
#' @param wt A numeric vector of observation weights (length n).
#' @param family A string: "binomial" or "poisson".
#' @param multiplier A numeric vector of per-variable penalty multipliers (length p).
#' @param penalty A string specifying the penalty: "LASSO", "MCP", or "SCAD".
#' @param lambda A numeric vector of penalty values, sorted in decreasing order.
#' @param alpha A numeric scalar for the elastic net mixing parameter.
#' @param gamma A numeric scalar for MCP and SCAD penalties.
#' @param lam_max A numeric scalar for the maximum lambda value.
#' @param max_iter An integer specifying the maximum total iterations.
#' @param dfmax An integer specifying the maximum number of selected variables.
#' @param eps A numeric scalar for the convergence tolerance.
#' @param user A logical flag for user-specified lambda starting behaviour.
#' @param warn A logical flag for saturation warnings.
#'
#' @return A list with beta0, beta, dev, eeta, and iter.
cd_wglm_fit_ssr <- function(X, y, wt, family, multiplier, penalty, lambda, alpha, gamma, lam_max, max_iter, dfmax, eps, user = FALSE, warn = TRUE) {
    .Call('_BRIER2_cd_wglm_fit_ssr', PACKAGE = 'BRIER2', X, y, wt, family, multiplier, penalty, lambda, alpha, gamma, lam_max, max_iter, dfmax, eps, user, warn)
}

#' Coordinate descent for BRIERs estimation procedure
#'
#' Coordinate-descent algorithm for penalized regression using summary
#' statistics and an LD reference panel.
#'
#' @param XtY A numeric vector of marginal correlations between genotype and outcome (length p).
#' @param ld_mat A p x p sparse matrix representing the linkage disequilibrium (LD) structure.
#' @param multiplier A numeric vector of per-variable penalty multipliers (length p).
#' @param penalty A string specifying the penalty: "LASSO", "MCP", or "SCAD".
#' @param lam A numeric vector of penalty values, sorted in decreasing order.
#' @param alpha A numeric scalar for the elastic net mixing parameter.
#' @param gamma A numeric scalar for MCP and SCAD penalties.
#' @param eps A numeric scalar for the convergence tolerance.
#' @param max_iter An integer specifying the maximum total iterations allowed.
#' @param dfmax An integer specifying the maximum number of selected variables.
#' @param user A logical flag. If TRUE, lambda is user-specified and iteration starts
#'   from the first value; if FALSE, the first lambda is skipped.
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{beta}{A matrix of coefficients (p x length(lam)).}
#'   \item{iter}{An integer vector of iteration counts for each lambda.}
#'   \item{df}{A numeric vector of degrees of freedom for each lambda.}
#'   \item{dev}{A numeric vector of deviance values for each lambda.}
#' }
cd_summary_fit <- function(XtY, ld_mat, multiplier, penalty, lam, alpha, gamma, eps, max_iter, dfmax, user) {
    .Call('_BRIER2_cd_summary_fit', PACKAGE = 'BRIER2', XtY, ld_mat, multiplier, penalty, lam, alpha, gamma, eps, max_iter, dfmax, user)
}

#' Maximum scaled inner product
#'
#' Compute the maximum scaled |X'r| / m(j) across all variables, treating
#' variables with m(j) == 0 as excluded from the maximum. Used for selecting
#' the maximum lambda in penalized regression with individual-level data.
#'
#' @param X An n x p numeric matrix.
#' @param r A numeric vector of length n.
#' @param n An integer specifying the number of rows.
#' @param p An integer specifying the number of columns.
#' @param m A numeric vector of per-variable scaling factors (length p).
#'   Variables with m(j) == 0 are skipped.
#'
#' @return A numeric scalar: the maximum value of |X'r|(j) / m(j).
maxprod <- function(X, r, n, p, m) {
    .Call('_BRIER2_maxprod', PACKAGE = 'BRIER2', X, r, n, p, m)
}

#' Maximum Lambda Selection for Summary Statistics
#'
#' Calculate the maximum lambda for LASSO when each SNP is its own group,
#' treating any SNP with m(j) == 0 as unpenalized. Iteratively fits the
#' unpenalized variables, then computes the marginal score for each
#' penalized variable.
#'
#' @param XtY A numeric vector (length p) of marginal correlations between
#'   genotype and outcome.
#' @param ld_mat A p x p sparse matrix representing the LD structure.
#' @param m A numeric vector of per-SNP scaling factors (length p).
#'   m(j) == 0 indicates an unpenalized variable.
#' @param alpha A numeric scalar for the elastic net mixing parameter.
#' @param eps A numeric scalar specifying the convergence threshold for the
#'   unpenalized update.
#' @param max_iter An integer specifying the maximum iterations for the
#'   unpenalized update.
#'
#' @return A numeric scalar: the maximum lambda value among penalized SNPs.
maxlambda_summary <- function(XtY, ld_mat, m, alpha, eps, max_iter) {
    .Call('_BRIER2_maxlambda_summary', PACKAGE = 'BRIER2', XtY, ld_mat, m, alpha, eps, max_iter)
}

#' Pseudo-validation score for summary-statistics models
#'
#' Compute a pseudo-validation score for each column of a coefficient matrix,
#' using a sparse LD reference (XtX) and a marginal correlation vector (r).
#' The score is defined as beta'r / sqrt(beta' XtX beta), and is used for
#' tuning lambda when validation data is unavailable.
#'
#' @param beta A p x L numeric matrix of coefficients across L lambda values.
#' @param XtX A p x p sparse LD reference matrix.
#' @param r A numeric vector (length p) of marginal correlations between
#'   genotype and outcome.
#'
#' @return A numeric vector of length L containing the pseudo-validation
#'   score for each lambda. Non-finite values (e.g. when beta is all zeros)
#'   are returned as NA.
pseudo_validation <- function(beta, XtX, r) {
    .Call('_BRIER2_pseudo_validation', PACKAGE = 'BRIER2', beta, XtX, r)
}

#' Standardize a design matrix
#'
#' Center and scale each column of X to have mean 0 and standard deviation 1.
#' Constant columns (sd = 0) are centered but not scaled.
#'
#' @param Xr An n x p numeric matrix.
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{standardized}{The standardized n x p matrix.}
#'   \item{center}{A numeric vector of length p of column means.}
#'   \item{scale}{A numeric vector of length p of column standard deviations.}
#' }
standardize_X <- function(Xr) {
    .Call('_BRIER2_standardize_X', PACKAGE = 'BRIER2', Xr)
}

#' Weighted standardization of a design matrix
#'
#' Center and scale each column of X using observation weights. Weights are
#' rescaled internally to sum to n for numerical stability.
#'
#' @param X An n x p numeric matrix.
#' @param wt A numeric vector of observation weights (length n).
#'
#' @return A list with the following elements:
#' \describe{
#'   \item{standardized}{The standardized n x p matrix.}
#'   \item{center}{A numeric vector of length p of weighted column means.}
#'   \item{scale}{A numeric vector of length p of weighted column standard deviations.}
#' }
wstandardize_X <- function(X, wt) {
    .Call('_BRIER2_wstandardize_X', PACKAGE = 'BRIER2', X, wt)
}

#' Unstandardize coefficients
#'
#' Given coefficients fitted on a standardized design matrix, recover the
#' coefficients on the original scale by reversing the centering and scaling.
#'
#' @param b0 A 1 x L matrix of intercepts (one per lambda).
#' @param b A p x L matrix of coefficients (one column per lambda).
#' @param scale A numeric vector of length p of column standard deviations.
#' @param center A numeric vector of length p of column means.
#' @param yy_center A numeric scalar (the response center, used for Gaussian models).
#' @param L An integer specifying the number of lambda values.
#' @param p An integer specifying the number of predictors.
#'
#' @return A (p+1) x L matrix where the first row is the unstandardized
#'   intercept and the remaining rows are the unstandardized coefficients.
unstand_beta <- function(b0, b, scale, center, yy_center, L, p) {
    .Call('_BRIER2_unstand_beta', PACKAGE = 'BRIER2', b0, b, scale, center, yy_center, L, p)
}

